export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';

export const ADD_TODO_ASYNC = 'ADD_TODO_ASYNC';
export const TOGGLE_TODO_ASYNC = 'TOGGLE_TODO_ASYNC';
export const DELETE_TODO_ASYNC = 'DELETE_TODO_ASYNC';
export const UPDATE_TODO_ASYNC = 'UPDATE_TODO_ASYNC';
